In [26]:
import pandas as pd
from tqdm.auto import tqdm

In [4]:
df = pd.read_csv(
    "/Users/cthoyt/.data/indra/db/processed_statements-2022-03-31-embeddings.tsv.gz",
    sep="\t",
)
df.head()

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.72 µs

,node,0,1,2,3,4,5,6,7,8,...,22,23,24,25,26,27,28,29,30,31
0,chebi:100,0.148108,0.074541,-0.147298,-0.016773,-0.169565,-0.226654,0.202802,-0.148013,-0.321001,...,0.008592,0.065432,-0.027748,-0.067200,0.137193,0.204892,-0.267319,0.218670,0.071785,-0.085332
1,chebi:10002,0.134803,-0.024014,-0.170718,0.241581,0.136230,0.168239,-0.181475,0.204359,-0.141766,...,0.022755,0.001614,0.465034,0.081675,0.103494,-0.166848,-0.216209,0.055532,-0.069520,-0.127041
2,chebi:10003,0.266829,-0.120007,-0.021270,0.148788,0.201040,-0.112230,0.009197,0.016800,-0.190698,...,0.088793,0.119266,-0.060036,-0.015827,-0.005601,-0.136979,-0.213992,-0.197851,-0.336797,0.111235
3,chebi:10014,0.009878,-0.167471,-0.298945,-0.038653,-0.238581,0.308835,-0.076348,0.017000,-0.319484,...,0.036818,-0.192034,0.173817,-0.118042,0.208547,-0.044534,-0.160867,-0.094434,0.145301,0.080382
4,chebi:100147,0.171220,-0.188367,0.120666,0.147350,-0.032833,0.139748,0.075386,0.040927,-0.128094,...,-0.189070,-0.046031,-0.273905,-0.000537,-0.182985,0.231589,-0.150930,0.208879,-0.041079,-0.152025

In [16]:
total = len(df.index)
total

20095023

In [13]:
synonyms_idx = df.node.str.startswith("text:")
grounded_idx = ~synonyms_idx

In [29]:
synonyms_path = "/Users/cthoyt/.data/indra/db/processed_statements-2022-03-31-synonyms.txt"
with open(synonyms_path, "w") as file:
    for s in tqdm(sorted(df.node[synonyms_idx]), unit_scale=True):
        print(s.removeprefix("text:").strip(), file=file)

  0%|          | 0.00/20.0M [00:00<?, ?it/s]

In [20]:
print(
    f"{grounded_idx.sum():,} ({grounded_idx.sum()/total:.2%}) are grounded, "
    f"{synonyms_idx.sum():,} ({synonyms_idx.sum()/total:.2%}) are not"
)

144,237 (0.72%) are grounded, 19,950,786 (99.28%) are not

In [21]:
df[synonyms_idx].head()

,node,0,1,2,3,4,5,6,7,8,...,22,23,24,25,26,27,28,29,30,31
97905,text: + + + nuclear extract : + + + + rna : ...,-0.228224,0.159510,0.069720,-0.195713,-0.138588,-0.169383,-0.259838,-0.232930,0.049245,...,0.342007,0.104673,0.211810,-0.018344,0.151354,-0.237777,-0.354250,0.193118,-0.158814,-0.384053
97906,text: inhibitory activity,-0.378138,0.173456,0.368705,0.284963,0.098901,0.392184,-0.022993,-0.110613,-0.303347,...,0.369152,0.075196,-0.236886,0.338369,0.036728,-0.023845,-0.093755,-0.170631,0.052966,-0.391528
97907,text: usually small size,0.221832,-0.048487,0.427949,0.156699,0.304542,0.406589,0.120966,-0.233858,-0.118984,...,-0.052563,-0.299463,0.411529,0.432976,-0.142404,0.049971,-0.140526,-0.061369,0.240630,0.375846
97908,text: %fl4 (f),-0.219200,-0.255034,0.229729,-0.223102,0.330264,0.294570,0.237043,0.004906,-0.281575,...,0.072373,-0.032502,-0.056107,0.109260,-0.140454,-0.023482,-0.096906,-0.116611,-0.036048,-0.247507
97909,text: (hsod1g93a),-0.094218,-0.215637,-0.176897,-0.226915,-0.350871,0.191455,0.033346,0.168944,-0.164959,...,0.175313,-0.271642,0.011002,0.186047,-0.189946,0.064753,-0.050520,0.201995,0.077354,-0.075646

In [25]:
for x in df.node[synonyms_idx].head(100):
    print(x.removeprefix("text:").lstrip())

+ + + nuclear extract :  + + + + rna : + + + + + ~[~ ~'~ ivse2 ~precgrsor "~
inhibitory activity
usually   small size
%fl4 (f)
(hsod1g93a)
(ryr2p2328s)
/
1 \\\\ l c tne
15 cm
15.5 41.33 + 30.14 0.50 4 39.75 _+ 7.3 36.4 _ 15.7 i.00 7 87.14 t 7.3* 61.43 + 8.12 *standard
33%
5 a/g snp
6 h
_i 4 ::~ ~ _
activated cd8(+) t cells
activator of nuclear factorkb
activators of p21
activators of p38\\u03b1
activators of p53
activators of parkin
activators of zbp89
activity of cytotoxic
activity of the cytotoxic
adaptor protein cbl
adherence
adherence and spreading
adhesion
adhesion of eosinophils
adhesion of monocytes
afghanistan
aggregate
aggregates and cell death
aggregation and apoptosis
allogeneic t cell proliferation ( )
allogeneic tcell
and a 3 rs
and a23187 (10 mum)
anergy
attachment
attachment and invasiveness
behavior
binding protein 2
blast
both aif and endo g
both apobec3g and apobec3f
both baff and april
both cd38 and hladr
both cdkn1c/p57, cdkn1b/p27 and arnt
both collagen and laminin
both cx32 and cx43
both cxcr7 and ccr10
both dat and \\u03b1synuclein
both dynactin and dynein
both estrogen receptor\\u03b1 and estrogen receptor\\u03b2
both eta and etb receptors
both g proteins and \\u03b2arrestins
both hsulf1 and hsulf2
both i\\u03bab and nf\\u03bab1
both ifn\\u03b3 and perforin
both il21 and il10
both il23 and il12
both ips1 and ticam1
both mafk and nrf2
both nesprin1 and nesprin2
both nod1 and nod2
both nomagap and rics
both pai1 and vitronectin
both shp2 and her2
both stat3 and stat5
both tbet and eomes
both xpc and ddb1
branching
cascades including erk/mapk
cascades including mapk, pi3k, and ralgtpase pathways
cascades including pi3k/akt
cascades including pi3kakt
cascades including pi3kakt, rac1cdc42
cascades including rafmekerk, phosphoinositide 3kinase and ral pathways
cascades including rasrafmekerk, pi3kakt, jnk
cascades including the akt/survivin
cascades including the mapk, pi3k stat
cascades including the mapk, pi3k, and nfkb pathways
cascades including the phosphatidylinositol 3kinase akt
cascades of mapk
ccr6+ cd4(+) t cells
ccr9+ t cells
cd14+ monocyte cultures ( )
cd14+ monocytes
cd16+ monocytes
cd16+/ monocytes
cd20+ b cell proliferation
cd23+cd5+ b cells
cd25(+)foxp3(+) t cells
cd25+ cd4+ t cells
cd25+ treg
cd25+cd4+ thymocytes
cd4+ t cell subset
cd4+ t cell subsets
cd45ra+cd4+ t cell proliferation ( )
cd8(+) t cell